"use client";
import {useMemo,useState} from "react";
import {PanelLeftClose,PanelLeftOpen,LayoutDashboard,FileText,MessageSquareText,Users,LogOut,Search,Plus,RefreshCw,ChevronLeft,ChevronRight,Phone,Mail,ShieldCheck,X,Save,CheckCircle2,AlertTriangle,Grid3X3,List,Clock3,ArrowUpRight,ArrowDownRight} from "lucide-react";
import policyData from "./data/policies.json";
type View="summary"|"policies"|"activity"|"clients";
type Status="renewable"|"upcoming"|"expired"|"active";
type Policy={id:number;name:string;initials:string;phone:string;email:string;type:string;insurer:string;due:string;days:number;status:Status;touches:number;note:string};
const data=policyData as Policy[];
const labels:Record<Status,string>={renewable:"Renovable",upcoming:"Próxima a vencer",expired:"Fuera de ventana",active:"Activa"};
const navigation:[View,typeof LayoutDashboard,string][]=[["summary",LayoutDashboard,"Resumen"],["policies",FileText,"Pólizas"],["activity",MessageSquareText,"Gestiones"],["clients",Users,"Clientes"]];
export default function Home(){
 const[policies,setPolicies]=useState(data),[view,setView]=useState<View>("summary"),[collapsed,setCollapsed]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState<Status|"all">("all"),[selected,setSelected]=useState<Policy|null>(null),[selectedClient,setSelectedClient]=useState<Policy|null>(null),[mode,setMode]=useState<"manage"|"renew"|null>(null),[notice,setNotice]=useState(""),[noticeLeaving,setNoticeLeaving]=useState(false);
 const shown=useMemo(()=>policies.filter(p=>(filter==="all"||p.status===filter)&&(`${p.name} ${p.insurer} ${p.type}`).toLowerCase().includes(query.toLowerCase())),[policies,query,filter]);
 const count=(s:Status)=>policies.filter(p=>p.status===s).length;
 function go(next:View){setView(next);setQuery("");setFilter("all")}
 function showNotice(message:string){setNoticeLeaving(false);setNotice(message);setTimeout(()=>setNoticeLeaving(true),2400);setTimeout(()=>setNotice(""),2900)}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const form=new FormData(e.currentTarget);if(mode==="renew"){setPolicies(all=>all.map(p=>p.id===selected.id?{...p,status:"active",due:String(form.get("date")),note:"Póliza renovada",touches:p.touches+1}:p));showNotice("Renovación registrada correctamente")}else{setPolicies(all=>all.map(p=>p.id===selected.id?{...p,note:String(form.get("note")),touches:p.touches+1}:p));showNotice("Gestión guardada correctamente")}setSelected(null);setMode(null)}
 function updatePhone(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selectedClient)return;const phone=String(new FormData(e.currentTarget).get("phone"));setPolicies(all=>all.map(p=>p.id===selectedClient.id?{...p,phone}:p));setSelectedClient(null);showNotice("Número de teléfono actualizado")}
 return <main className={collapsed?"shell collapsed":"shell"}>
  <aside className="sidebar"><button className="collapse" onClick={()=>setCollapsed(!collapsed)} aria-label={collapsed?"Expandir menú":"Colapsar menú"}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><div className="avatar">MG</div><nav>{navigation.map(([key,Icon,label])=><button key={key} className={view===key?"active":""} onClick={()=>go(key)} title={label}><span><Icon/></span><b>{label}</b></button>)}</nav><button className="logout" title="Cerrar sesión"><span><LogOut/></span><b>Salir</b></button></aside>
  <section className="canvas"><Header view={view} query={query} setQuery={setQuery}/>
   {view==="summary"&&<Summary policies={policies} count={count} openPolicies={()=>go("policies")}/>}
   {view==="policies"&&<Policies policies={shown} query={query} filter={filter} setFilter={setFilter} open={(p,m)=>{setSelected(p);setMode(m)}}/>}
   {view==="activity"&&<Activity policies={policies} open={p=>{setSelected(p);setMode("manage")}}/>}
   {view==="clients"&&<Clients policies={shown} open={setSelectedClient}/>}
  </section>
  {notice&&<div className={noticeLeaving?"toast toast-leaving":"toast"}><ShieldCheck/> {notice}</div>}
  {selected&&<div className="backdrop modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><div className="modal-heading"><span className="modal-symbol">{mode==="renew"?<RefreshCw/>:<Plus/>}</span><div><p className="kicker">{selected.type} · {selected.insurer}</p><h2>{mode==="renew"?"Renovar póliza":"Registrar gestión"}</h2></div></div><p>Cliente: <strong>{selected.name}</strong></p><form onSubmit={submit}>{mode==="manage"?<><label>Resultado<select><option>Cliente contactado</option><option>No contestó</option><option>Interesado</option><option>No interesado</option></select></label><label>Nota<textarea name="note" required placeholder="Resultado y próximo paso…"/></label></>:<label>Nueva fecha de vencimiento<input name="date" type="date" min="2026-08-21" required/></label>}<div className="modal-actions"><button className="modal-cancel" type="button" onClick={()=>setSelected(null)}>Cancelar</button><button className="modal-confirm">{mode==="renew"?"Confirmar renovación":"Guardar gestión"}</button></div></form></div></div>}
  {selectedClient&&<div className="backdrop modal-backdrop" onMouseDown={()=>setSelectedClient(null)}><div className="modal client-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelectedClient(null)}><X/></button><div className="client-hero"><span>{selectedClient.initials}</span><div><p className="kicker">DETALLE DEL CLIENTE</p><h2>{selectedClient.name}</h2></div></div><div className="read-only"><Mail/><div><small>Correo electrónico</small><strong>{selectedClient.email}</strong></div></div><div className="read-only"><ShieldCheck/><div><small>Póliza actual</small><strong>{selectedClient.type} · {selectedClient.insurer}</strong></div></div><form onSubmit={updatePhone}><label className="phone-label"><Phone/> Número de teléfono<input name="phone" defaultValue={selectedClient.phone} required pattern="[0-9 +()-]{7,20}"/></label><p className="edit-hint">Solo este campo puede editarse en la demo.</p><div className="modal-actions"><button className="modal-cancel" type="button" onClick={()=>setSelectedClient(null)}>Cancelar</button><button className="modal-confirm"><Save/> Actualizar</button></div></form></div></div>}
 </main>
}
function Header({view,query,setQuery}:{view:View;query:string;setQuery:(v:string)=>void}){const titles={summary:"Panel de renovaciones",policies:"Pólizas",activity:"Gestiones comerciales",clients:"Clientes"};return <header><div><p className="kicker">AGENTEMOTO · 20 AGOSTO 2026</p><h1>{titles[view]}</h1></div><label className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, póliza…"/><span><Search/></span></label></header>}
function Summary({policies,count,openPolicies}:{policies:Policy[];count:(s:Status)=>number;openPolicies:()=>void}){return <div className="dashboard">
 <section className="card focus-card redesigned"><div className="card-head"><div><p className="kicker">PRIORIDAD DE HOY</p><h2>Ventana comercial</h2></div><select><option>Esta semana</option></select></div><div className="priority-hero"><div className="priority-total"><span>{count("renewable")+count("upcoming")}</span><div><b>casos por atender</b><small>Ordenados por urgencia comercial</small></div></div><div className="priority-split"><article><span className="metric-arrow up"><ArrowUpRight/></span><div><strong>{count("renewable")}</strong><p>Renovables</p><small>Contactar hoy</small></div></article><article><span className="metric-arrow down"><ArrowDownRight/></span><div><strong>{count("expired")}</strong><p>Fuera de ventana</p><small>Requieren revisión</small></div></article></div></div><div className="priority-tip"><Clock3/><span><b>3 llamadas recomendadas</b><small>Empieza por los casos con menos días disponibles.</small></span></div></section>
 <PolicyCalendar policies={policies}/>
 <section className="card progress-card redesigned activity-card"><div><p className="kicker">ACTIVIDAD DEL MES</p><h2>Ritmo operativo</h2></div><div className="activity-total"><span><MessageSquareText/></span><div><strong>{policies.reduce((sum,p)=>sum+p.touches,0)}</strong><b>gestiones registradas</b><small>Actividad acumulada en la cartera</small></div></div><div className="activity-breakdown"><article><span>18</span><div><b>Contactos</b><small>llamadas y mensajes</small></div></article><article><span>6</span><div><b>Seguimientos</b><small>requieren nueva acción</small></div></article><article><span>3</span><div><b>Documentos</b><small>pendientes por recibir</small></div></article></div><div className="activity-week"><div className="mini-columns">{[38,62,48,76,58,84,70].map((value,i)=><i key={i} style={{height:`${value}%`}}></i>)}</div><div><b>+12%</b><small>actividad frente a la semana anterior</small></div></div></section>
 <section className="card trend"><div className="card-head"><div><p className="kicker">DESEMPEÑO</p><h2>Gestión semanal</h2></div><select><option>Últimos 7 días</option></select></div><div className="chart"><svg viewBox="0 0 600 180" preserveAspectRatio="none"><defs><linearGradient id="violetFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6662db" stopOpacity=".26"/><stop offset="100%" stopColor="#6662db" stopOpacity="0"/></linearGradient><linearGradient id="orangeFade" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff8a52" stopOpacity=".20"/><stop offset="100%" stopColor="#ff8a52" stopOpacity="0"/></linearGradient></defs><path className="area violet-area" d="M0 125 C55 115 55 72 80 72 S135 120 160 120 S215 88 240 88 S295 136 320 136 S375 48 400 48 S455 92 480 92 S560 54 600 54 L600 180 L0 180 Z"/><path className="area orange-area" d="M0 145 C45 140 55 110 80 110 S135 128 160 128 S215 75 240 75 S295 105 320 105 S375 98 400 98 S455 42 480 42 S560 122 600 122 L600 180 L0 180 Z"/><path className="smooth-line" d="M0 125 C55 115 55 72 80 72 S135 120 160 120 S215 88 240 88 S295 136 320 136 S375 48 400 48 S455 92 480 92 S560 54 600 54"/><path className="smooth-line orange-line" d="M0 145 C45 140 55 110 80 110 S135 128 160 128 S215 75 240 75 S295 105 320 105 S375 98 400 98 S455 42 480 42 S560 122 600 122"/></svg></div><div className="legend"><span className="violet-dot">Gestiones</span><span className="orange-dot">Renovaciones</span></div></section>
 <Effectiveness rate={75} target={67} openPolicies={openPolicies}/>
 <RiskQueue policies={policies}/>
 </div>}
const monthNames=["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];
function PolicyCalendar({policies}:{policies:Policy[]}){const[date,setDate]=useState(new Date(2026,7,1));const year=date.getFullYear(),month=date.getMonth(),days=new Date(year,month+1,0).getDate(),offset=(new Date(year,month,1).getDay()+6)%7;const dueDates=policies.filter(p=>p.status==="upcoming").map(p=>p.due.toLowerCase());const isDue=(day:number)=>dueDates.some(d=>d.startsWith(String(day).padStart(2,"0"))&&d.includes(monthNames[month].slice(0,3).toLowerCase())&&d.includes(String(year)));const move=(delta:number)=>setDate(new Date(year,month+delta,1));return <section className="card calendar"><div className="card-head"><button onClick={()=>move(-1)} aria-label="Mes anterior"><ChevronLeft/></button><h2>{monthNames[month]} {year}</h2><button onClick={()=>move(1)} aria-label="Mes siguiente"><ChevronRight/></button></div><div className="week">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(x=><b key={x}>{x}</b>)}{Array.from({length:offset},(_,i)=><span className="empty-day" key={`e${i}`}></span>)}{Array.from({length:days},(_,i)=><span key={i} className={isDue(i+1)?"due-day":(year===2026&&month===7&&i+1===20)?"today":""}>{i+1}</span>)}</div><div className="calendar-keys"><span><i className="today-key"></i>Hoy</span><span><i className="due-key"></i>Vencimiento próximo</span></div></section>}
function Effectiveness({rate,target,openPolicies}:{rate:number;target:number;openPolicies:()=>void}){const positive=rate>=target;return <section className="card gauge"><p className="kicker">EFECTIVIDAD</p><h2>Tasa de renovación</h2><div className="ring modern-ring" style={{"--rate":`${rate}%`} as React.CSSProperties}><div><strong>{rate}%</strong><small>de efectividad</small></div></div><div className={positive?"goal-note positive":"goal-note negative"}>{positive?<CheckCircle2/>:<AlertTriangle/>}<span>{positive?`Superas en ${rate-target}% la meta del mes`:`Estás ${target-rate}% por debajo de la meta`}</span></div><button className="accent" onClick={openPolicies}>Ver pólizas</button></section>}
function RiskQueue({policies}:{policies:Policy[]}){const priority=policies.filter(p=>p.status==="renewable"||p.status==="upcoming").slice(0,3);return <section className="card status-card risk-card"><div className="card-head"><div><p className="kicker">ACCIÓN RECOMENDADA</p><h2>Próximos contactos</h2></div><Clock3/></div>{priority.map(p=><article key={p.id}><span className={`risk-icon ${p.status}`}>{p.initials}</span><div><b>{p.name}</b><small>{p.status==="renewable"?`Venció hace ${p.days} días`:`Vence en ${p.days} días`}</small></div><em>{p.touches?"Seguimiento":"Contactar"}</em></article>)}</section>}
function Policies({policies,filter,setFilter,open}:{policies:Policy[];query:string;filter:Status|"all";setFilter:(v:Status|"all")=>void;open:(p:Policy,m:"manage"|"renew")=>void}){return <section className="card page-card"><div className="page-tools"><div><p className="kicker">COLA DE TRABAJO</p><h2>{policies.length} pólizas encontradas</h2></div><select value={filter} onChange={e=>setFilter(e.target.value as Status|"all")}><option value="all">Todos los estados</option><option value="renewable">Renovables</option><option value="upcoming">Próximas</option><option value="expired">Fuera de ventana</option><option value="active">Activas</option></select></div><div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Póliza</th><th>Vencimiento</th><th>Estado</th><th>Última gestión</th><th>Acciones</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td><div className="person"><span>{p.initials}</span><div><b>{p.name}</b><small>{p.phone}</small></div></div></td><td><b>{p.type}</b><small>{p.insurer}</small></td><td><b>{p.due}</b></td><td><span className={`pill ${p.status}`}><i></i>{labels[p.status]}</span></td><td><b>{p.note}</b><small>{p.touches} gestiones</small></td><td><div className="row-actions"><button onClick={()=>open(p,"manage")}>Gestionar</button><button className="accent" disabled={p.status==="active"} onClick={()=>open(p,"renew")}>Renovar</button></div></td></tr>)}</tbody></table></div></section>}
function Activity({policies,open}:{policies:Policy[];open:(p:Policy)=>void}){const managed=policies.filter(p=>p.touches>0).sort((a,b)=>b.touches-a.touches);return <div className="activity-grid"><section className="card page-card"><p className="kicker">HISTORIAL ACTUALIZADO</p><h2>Gestiones registradas desde Pólizas</h2><div className="timeline">{managed.map((p,i)=><article key={p.id}><span>{p.initials}</span><div><b>{p.name}</b><p>{p.note}</p><small>{i===0?"Actualizada recientemente":`Registro ${i+1}`} · {p.touches} gestiones</small></div><button onClick={()=>open(p)} aria-label={`Agregar gestión a ${p.name}`}><Plus/></button></article>)}</div></section><section className="card mini-stats"><p className="kicker">RESULTADOS</p><h2>Esta semana</h2><div className="donut"><strong>{managed.reduce((sum,p)=>sum+p.touches,0)}</strong><span>gestiones</span></div><ul><li><i></i>Clientes gestionados <b>{managed.length}</b></li><li><i></i>Renovables <b>{managed.filter(p=>p.status==="renewable").length}</b></li><li><i></i>Próximas <b>{managed.filter(p=>p.status==="upcoming").length}</b></li></ul></section></div>}
function Clients({policies,open}:{policies:Policy[];open:(p:Policy)=>void}){const[display,setDisplay]=useState<"grid"|"list">("grid");return <section className="card page-card clients-page"><div className="page-tools"><div><p className="kicker">DIRECTORIO</p><h2>{policies.length} clientes activos</h2></div><div className="view-switch" aria-label="Cambiar vista"><button className={display==="grid"?"active":""} onClick={()=>setDisplay("grid")} title="Vista en cuadros"><Grid3X3/></button><button className={display==="list"?"active":""} onClick={()=>setDisplay("list")} title="Vista en lista"><List/></button></div></div><div key={display} className={display==="grid"?"client-grid view-enter":"client-list view-enter"}>{policies.map(p=><article key={p.id}><div className="client-identity"><span className="client-avatar">{p.initials}</span><h3>{p.name}</h3></div><div className="client-contact email-contact"><Mail/><span>{p.email}</span></div><div className="client-contact phone-contact"><Phone/><span>{p.phone}</span></div><div className="client-policy"><b>{p.type}</b><small>{p.insurer}</small></div><button className="detail-button" onClick={()=>open(p)}>Ver detalle</button></article>)}</div></section>}
